version: "3.8"
services:
  redis:
    container_name: "redis"
    image: hub.hamdocker.ir/redis:7-alpine
    volumes:
      - ./data:/data
    env_file:
      - ./env.env
    networks:
      app-net:
        aliases:
          - redis


  app:
    build:
      context: .
      target: runner
    container_name: "app"
    depends_on:
      - redis
    ports:
      - 8080:8080
    env_file:
      - ./env.env
    networks:
      - app-net
    configs:
      - source: app-conf
        target: /config.json




networks:
  app-net:
    driver: bridge

configs:
  app-conf:
    file: ./config.json


